core/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form = LoginForm), name="login"),
    path('logout/', views.logged_out, name='logout'),
]

dashboard/urls.py
from django.urls import path
from . import views


app_name = 'dashboard'

urlpatterns = [
    path('dashboard/', views.my_dashboard, name='dashboard')  ,  
    

]

item/urls.py
from django.urls import path
from . import views


app_name = 'item'

urlpatterns = [
    path('new_item/', views.new_item, name='new_item')  ,  
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit', views.edit_item, name='edit'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('admin/', admin.site.urls),
    path('items/', include('item.urls', namespace='item')),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

item/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=255)


    class Meta():
        ordering = ('name',)
        verbose_name_plural = "Categories"


    def __str__(self):
        return self.name 
    
class Item (models.Model):
    category=models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name=models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image= models.ImageField(upload_to='item_image', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by  = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username ',
        'class':'w-full py-4 px-6 rounded-xl'
    }))    

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password ',
        'class':'w-full py-4 px-6 rounded-xl'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username ',
        'class':'w-full py-4 px-6 rounded-xl'
    }))    
    email= forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your Email address',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password ',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm your password ',
        'class':'w-full py-4 px-6 rounded-xl'
    })) 

item/forms.py
from django import forms
from .models import Item


INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['category','name','description','price','image']
        widgets = {
            'category' : forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name' : forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description' : forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price' : forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image' : forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name','description','price','image', 'is_sold']
        widgets = {
            'name' : forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description' : forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price' : forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image' : forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }        

core/views.py
from django.shortcuts import redirect, render
from item.models import Item, Category
from .forms import SignupForm
from django.contrib.auth import logout
from django.contrib import messages
# from django.urls import reverse

# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact (request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:  

        form = SignupForm()
    return render(request, 'core/signup.html',{'form': form })


def logged_out (request):
    logout(request)
    return redirect('/login/')

dashboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from item.models import Item
from django.contrib.auth.decorators import login_required

# Create your views here.


def my_dashboard(request):
    items = Item.objects.filter(created_by=request.user)

    return  render(request, 'dashboard/my_dashboard.html',{
        'items':items
    })




@login_required
def delete (request, pk):
    item = get_object_or_404(Item, pk=pk, created_by = request.user)
    item.delete()

    return redirect('dashboard:dashboard')

item/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Item
from .forms import NewItemForm, EditItemForm


def detail (request, pk):
    item = get_object_or_404(Item, pk=pk)
    realted_items =Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item ,
        'realted_items': realted_items
        })

@login_required
def new_item(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST , request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail' , pk=item.id)
        
    else:   
        form = NewItemForm

    return render(request, 'item/add_item.html', {
        'form' : form,
        'title ': 'New Item'
    })


@login_required
def edit_item(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by = request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST , request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail' , pk=item.id)
        
    else:   
        form = NewItemForm(instance=item)

    return render(request, 'item/add_item.html', {
        'form' : form,
        'title ': 'Edit Item'
    })


@login_required
def delete (request, pk):
    item = get_object_or_404(Item, pk=pk, created_by = request.user)
    item.delete()

    return redirect('dashboard:dashboard')

templates/core/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width , initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>
        <title>{% block title %} {%endblock%} | Prestige</title>
    </head>
    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semiblod">Prestige</a>
            <div class="space-x-6">
                <a href="{% url 'item:new_item'%}" class="text-lg font-semiblod hover:text-gray-500">New Item</a>
                <a href="{% url 'core:index' %}" class="text-lg font-semiblod hover:text-gray-500">Browse</a>
                {%if request.user.is_authenticated %}
                <a href="#" class="px-6 py-3 text-lg font-semiblod bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                <a href="{% url 'dashboard:dashboard' %}" class="px-6 py-3 text-lg font-semiblod bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semiblod bg-teal-500 text-white rounded-xl hover:bg-teal-700">Logout</a>
                {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semiblod bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semiblod bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}
            </div>
        </nav>
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>
        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semiblod text-gray-400"><b>About</b></h3>
                <p style="color:rgba(245, 240, 240, 0.955);">Welcome to Prestige, your premier online marketplace where quality meets convenience. At Prestige, we bring together a curated selection of top-tier products from trusted vendors, ensuring that every purchase is a step toward luxury and satisfaction. Whether you're seeking the latest in fashion, cutting-edge electronics, or unique home decor, our platform offers an unparalleled shopping experience designed with your needs in mind. Explore our diverse catalog, enjoy seamless transactions, and discover why Prestige is the go-to destination for discerning shoppers.</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semiblod text-gray-400"><Menu></h3>
                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
                </ul>    
            </div>
        </footer>
    </body>
</html>

templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %} Contact {%endblock%} 

{% block content %}
    <h1>The Contact Page</h1>
{% endblock %}

templates/core/index.html
{% extends 'core/base.html' %}

{% block title %} Welcome {%endblock%} 

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest Items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url}}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500"> Price : {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}    
        </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories%}
            <div>
                <a href="#">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ category.name }}</h2>
                        <p class="text-gray-500"> Price : {{ category.items.count }} Items</p>
                    </div>
                </a>
            </div>

            {% endfor %}
        </div>


{% endblock %}

templates/core/login.html
{% extends 'core/base.html' %}


{% block title %} Login {% endblock %}

{% block content %}

<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">SignIn</h1>
    
    <form method="POST" enctype="multipart/form-data" >
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>
        
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>
       
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}

            {% endfor %}
            
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounder-xl text-white" type="submit">Submit</button>
    </form>
    
</div>

{% endblock%}

templates/core/logout.html
{% extends "base.html" %}
 {% block title %} Logged Out {% endblock%}

{% block content %}
  <p>Logged out!</p>
  <a href="{% url 'login'%}">Click here to login again.</a>
{% endblock %}

templates/core/signup.html
{% extends 'core/base.html' %}


{% block title %} Sign Up {% endblock %}

{% block content %}

<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign Up</h1>

    <form method="POST" enctype="multipart/form-data" >
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Confirm Password</label><br>
            {{ form.password2 }}
        </div>
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}

            {% endfor %}
            
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounder-xl text-white" type="submit">Submit</button>
    </form>
</div>

{% endblock%}

templates/dashboard/my_dashboard.html
{% extends 'core/base.html' %}

{% block title %} Dashboard {%endblock%} 

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">My Items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url}}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500"> Price : {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}    
       

{% endblock %}

templates/item/add_item.html
{% extends 'core/base.html' %}

{% block title %}{{ title }} {% endblock %}

{% block content %}

<h1 class="mb-6 text-3xl">{{ title }}</h1>
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>
 
    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}

            {% endfor %}
            
            {{ form.non_field_errors }}
        </div>
    {% endif %}
  
    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounder-xl text-white" type="submit">Submit</button>
</form>
{% endblock %}

templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{%endblock%}
{%block content %} 
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.image.url }}" class="rounded-xl">
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <p class="test-gray-500"><strong>Price: </strong>{{ item.price }} $</p>
        <p class="test-gray-500"><strong>Seller: </strong>{{ item.created_by.username }}</p>

        {% if item.description %}
        <p class="text-gray-700">
            <strong class="text-gray-500">Description:</strong><br>
            {{ item.description }}
        </p>
        {% endif %}

        {% if request.user == item.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl" %>
                <p> This is your Item !</p>
                <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semiblod bg-teal-500 text-white rounded-xl"> Edit </a>
                <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semiblod bg-red-500 text-white rounded-xl"> Delete </a>
            </div>
        {% else %}
            
        <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact Seller</a>
        {% endif %}
    </div>
</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related Items</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in realted_items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500"> Price : {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}    
    </div>
</div>    
{%endblock%}